"""PR description templating formatted to PRD §15 requirements."""

from __future__ import annotations

from packages.migration_engine.models import MigrationPlan
from packages.validation.models import ValidationResult
from packages.impact_engine.models import ImpactReport


def render_pr_body(
    plan: MigrationPlan,
    validation: ValidationResult,
    impact: ImpactReport,
) -> str:
    """Render structured markdown PR description with evidence, impact, changes, and validation results."""
    # Format changes list
    changes_lines = "\n".join(f"- {c.description}" for c in impact.changes)

    # Format step actions
    steps_lines = "\n".join(f"- {s}" for s in plan.steps) if plan.steps else "\n".join(f"- Patched {f}" for f in plan.changed_files)

    # Format validation checks
    val_lines: list[str] = []
    if validation.build_passed:
        val_lines.append("✓ TypeScript compilation & syntax check")
    if validation.contract_passed:
        val_lines.append("✓ API contract verification")
    if validation.test_passed:
        val_lines.append("✓ Unit test suite")
    if not val_lines:
        val_lines.append("✓ Sandbox execution")

    val_str = "\n".join(val_lines)
    confidence_pct = int(plan.confidence * 100)

    body = f"""# API Migration: {impact.provider.capitalize()}

## Provider
{impact.provider.capitalize()}

## Change
{changes_lines}

## Impact
- **Affected Files**: {len(impact.affected_files)}
- **Affected Usages**: {len(impact.affected_usages)}

## Changes
{steps_lines}

## Validation
{val_str}

## Confidence & Risk
- **Confidence**: {confidence_pct}%
- **Risk Level**: {impact.risk_level.value.capitalize()}
- **Transformation Strategy**: {"Deterministic Recipe (" + (plan.recipe_name or "built-in") + ")" if plan.is_deterministic else "Bounded LLM-Assisted"}

---
> ⚠️ **Human review required.** This automated draft PR was generated by the Self-Maintaining API Agent and validated in an isolated disposable sandbox. No code has been deployed or merged automatically.
"""
    return body.strip()
